default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: text_development

test:
  <<: *default
  database: text_test

production:
  <<: *default
  database: text
